{% set name = "robotframework-browser" %}
{% set version = "2.2.0" %}
{% set grpcio_version = "1.33.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4dce0330539e24e91f1af2ed0bb852fb12108036440f76d4730e05191993bb60

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv && rfbrowser init
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - nodejs
    - backports.cached-property
    - grpcio =={{ grpcio_version }}
    - grpcio-tools =={{ grpcio_version }}
    - robotframework >=3.2.2
    - robotframework-pythonlibcore >=2.1.0
    - typing-extensions >=3.7.4.3
    - wrapt
  run:
    - python
    - nodejs
    - backports.cached-property
    - grpcio =={{ grpcio_version }}
    - grpcio-tools =={{ grpcio_version }}
    - robotframework >=3.2.2
    - robotframework-pythonlibcore >=2.1.0
    - typing-extensions >=3.7.4.3
    - wrapt

test:
  imports:
    - Browser

about:
  home: https://github.com/MarketSquare/robotframework-browser
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Robot Framework Browser library powered by Playwright.
  description: |
    Robot Framework Browser library powered by Playwright. Moving browser automation to year 2020 (or 2021)!
    Aiming for speed, reliability and visibility.
  doc_url: https://marketsquare.github.io/robotframework-browser/Browser.html
  dev_url: https://github.com/MarketSquare/robotframework-browser

extra:
  recipe-maintainers:
    - martinRenou
    - xylix
